[package]
name = "femtovg"
description = "Antialiased 2D vector drawing library"
version = "0.1.1"
license = "MIT/Apache-2.0"
readme = "README.md"
authors = ["Peter Todorov <ptodorov@cytec.bg>", "Adam Nemecek <adamnemecek@gmail.com>"]
keywords = ["graphics", "canvas", "vector", "drawing", "gpu"]
categories = ["graphics"]
repository = "https://github.com/femtovg/femtovg"
edition = "2018"

[profile.release]
debug = true

[dependencies]
fnv = "1.0.7"
rgb = "0.8.20"
imgref = "1.6.1"
bitflags = "1.2.1"
owned_ttf_parser = "0.6.0"
rustybuzz = "0.3.0"
unicode-bidi = "0.3.4"
unicode-segmentation = "1.6.0"
generational-arena = "0.2.8"
lru = { version = "0.5.3", default-features = false }
image = { version = "0.23.6", optional = true, default-features = false }
serde = { version = "1.0", optional = true, features = ["derive"] }
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs/" , rev = "5d2e88c6c8942e546b9b7da89be9408a6cd6b31c" }
#wgpu = { git = "https://github.com/gfx-rs/wgpu-rs/" , features = ["trace"], rev = "0f1b290af947d3cd16280c4eb3b48507f5e6c9fb" }
pollster = "0.2"
winit = { version = "0.24", default-features = false }
#winit = { git = "https://github.com/adamnemecek/winit", rev = "8fb77892bdb785045396700391195b10eaf656d8" }
#metal = { rev = "439c986eb7a9b91e88b61def2daa66e4043fcbef" }
ngds = { git = "https://github.com/adamnemecek/ngds", branch = "main" }
mem_align = { git = "https://github.com/adamnemecek/mem_align/", branch = "main" }
static_assertions = "*"

#git = "https://github.com/gfx-rs/gfx"
#rev = "" # insert revision here
#features = ["auto-capture"]

#gfx = { git = "https://github.com/gfx-rs/gfx",rev = "be631cb4a008f5a52a7b689ddc188a19699ef089#be631cb4a008f5a52a7b689ddc188a19699ef089", features = ["metal", "auto-capture"] }

# [target.'cfg(any(target_os = "ios", target_os = "macos"))'.dependencies.gfx-backend-metal]
# git = "https://github.com/gfx-rs/gfx"
# rev = "be631cb4a008f5a52a7b689ddc188a19699ef089" # insert revision here
# features = ["auto-capture"]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
glow = { version = "0.7.0", default-features = false }

[target.'cfg(target_arch = "wasm32")'.dependencies]
glow = { version = "0.7.0", features = ["web-sys"], default-features = false }
web_sys = { version = "0.3", package = "web-sys", features = ["WebGlContextAttributes", "HtmlImageElement"] }
wasm-bindgen = { version = "=0.2.73" }

[features]
default = ["image-loading", "convert-rgb"]
image-loading = ["image"]
debug_inspector = []
convert-rgb = []

[dev-dependencies]

euclid = "0.20.13"
rand = "0.7"
svg = "0.8.0"
usvg = { version = "0.12.0", default-features = false }
instant = { version = "0.1", features = [ "now" ] }
resource = "0.5.0"
image = { version = "0.23.6", default-features = false, features = ["jpeg", "png"] }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
glutin = "0.26.0"

# [target.'cfg(target_arch = "wasm32")'.dev-dependencies]
# winit = { version = "0.24", default-features = false, features = ["web-sys"] }

# wasm-bindgen = { version = "0.2" }
# web_sys = { version = "=0.3.50", package = "web-sys", features=["console", "WebGlContextAttributes"] }
# console_error_panic_hook = "0.1.5"
# instant = { version = "0.1", features = [ "wasm-bindgen", "now" ] }
# resource = { version = "0.5.0", features = [ "force-static" ] }
