[package]
name = "femtovg"
description = "Antialiased 2D vector drawing library"
version = "0.1.1"
license = "MIT/Apache-2.0"
readme = "README.md"
authors = ["Peter Todorov <ptodorov@cytec.bg>", "Adam Nemecek <adamnemecek@gmail.com>"]
keywords = ["graphics", "canvas", "vector", "drawing", "gpu"]
categories = ["graphics"]
repository = "https://github.com/femtovg/femtovg"
edition = "2018"

[profile.release]
debug = true

[features]
default = ["image-loading", "convert-rgb", "glow-renderer"]
image-loading = ["image"]
glow-renderer = ["glow"]
wgpu-renderer = ["wgpu", "raw-window-handle"]
debug_inspector = []
convert-rgb = []

[dependencies]
fnv = "1.0.7"
rgb = "0.8.20"
imgref = "1.6.1"
bitflags = "1.2.1"
owned_ttf_parser = "0.6.0"
rustybuzz = "0.3.0"
unicode-bidi = "0.3.4"
unicode-segmentation = "1.6.0"
generational-arena = "0.2.8"
lru = { version = "0.5.3", default-features = false }
image = { version = "0.23.6", optional = true, default-features = false }
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs/" , rev = "82b7068498864de44bbdf3e02d086c03d83a04e0", optional = true }
raw-window-handle = { version = "0.3.3", optional = true }
#metal = { rev = "439c986eb7a9b91e88b61def2daa66e4043fcbef" }

#git = "https://github.com/gfx-rs/gfx"
#rev = "" # insert revision here
#features = ["auto-capture"]

#gfx = { git = "https://github.com/gfx-rs/gfx",rev = "be631cb4a008f5a52a7b689ddc188a19699ef089#be631cb4a008f5a52a7b689ddc188a19699ef089", features = ["metal", "auto-capture"] }

# [target.'cfg(any(target_os = "ios", target_os = "macos"))'.dependencies.gfx-backend-metal]
# git = "https://github.com/gfx-rs/gfx"
# rev = "be631cb4a008f5a52a7b689ddc188a19699ef089" # insert revision here
# features = ["auto-capture"]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
glow = { version = "0.7.0", default-features = false, optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
glow = { version = "0.7.0", features = ["web-sys"], default-features = false, optional = true }
web_sys = { version = "0.3", package = "web-sys", features = ["WebGlContextAttributes", "HtmlImageElement"] }
wasm-bindgen = { version = "=0.2.73" }

[dev-dependencies]
euclid = "0.20.13"
rand = "0.7"
svg = "0.8.0"
usvg = { version = "0.12.0", default-features = false }
instant = { version = "0.1", features = [ "now" ] }
resource = "0.5.0"
image = { version = "0.23.6", default-features = false, features = ["jpeg", "png"] }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
winit = "0.24.0"
glutin = "0.26.0"
pollster = "0.2"

# [target.'cfg(target_arch = "wasm32")'.dev-dependencies]
# winit = { version = "0.24", default-features = false, features = ["web-sys"] }

# wasm-bindgen = { version = "0.2" }
# web_sys = { version = "=0.3.50", package = "web-sys", features=["console", "WebGlContextAttributes"] }
# console_error_panic_hook = "0.1.5"
# instant = { version = "0.1", features = [ "wasm-bindgen", "now" ] }
# resource = { version = "0.5.0", features = [ "force-static" ] }
