[package]
name = "femtovg"
description = "Antialiased 2D vector drawing library"
version = "0.1.1"
license = "MIT/Apache-2.0"
readme = "README.md"
authors = ["Peter Todorov <ptodorov@cytec.bg>", "Adam Nemecek <adamnemecek@gmail.com>"]
keywords = ["graphics", "canvas", "vector", "drawing", "gpu"]
categories = ["graphics"]
repository = "https://github.com/femtovg/femtovg"
edition = "2018"

[profile.release]
debug = true

[features]
default = ["image-loading", "convert-rgb", "wgpu-renderer"]
image-loading = ["image"]
glow-renderer = ["glow"]
wgpu-renderer = ["wgpu"]
debug_inspector = []
convert-rgb = []

[dependencies]
fnv = "1.0.7"
rgb = "0.8.20"
imgref = "1.6.1"
bitflags = "1.2.1"
owned_ttf_parser = "0.6.0"
rustybuzz = "0.3.0"
unicode-bidi = "0.3.4"
unicode-segmentation = "1.6.0"
generational-arena = "0.2.8"
lru = { version = "0.5.3", default-features = false }
image = { version = "0.23.6", optional = true, default-features = false }
serde = { version = "1.0", optional = true, features = ["derive"] }
pollster = "0.2"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
glow = { version = "0.7.0", default-features = false, optional = true }
wgpu = { version = "0.7.1", optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
glow = { version = "0.7.0", features = ["web-sys"], default-features = false }
wgpu = { version = "0.7.1", features = ["wgc"], optional = true }
web_sys = { version = "0.3", package = "web-sys", features = ["WebGlContextAttributes", "HtmlImageElement"] }
wasm-bindgen = { version = "=0.2.69" }

[dev-dependencies]
winit = "0.24.0"
euclid = "0.20.13"
rand = "0.7"
svg = "0.8.0"
usvg = { version = "0.12.0", default-features = false }
instant = { version = "0.1", features = [ "now" ] }
resource = "0.5.0"
image = { version = "0.23.6", default-features = false, features = ["jpeg", "png"] }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
glutin = "0.26.0"

# [target.'cfg(target_arch = "wasm32")'.dev-dependencies]
# winit = { version = "0.24", default-features = false, features = ["web-sys"] }

# wasm-bindgen = { version = "0.2" }
# web_sys = { version = "=0.3.50", package = "web-sys", features=["console", "WebGlContextAttributes"] }
# console_error_panic_hook = "0.1.5"
# instant = { version = "0.1", features = [ "wasm-bindgen", "now" ] }
# resource = { version = "0.5.0", features = [ "force-static" ] }
